### ISSUE TITLE
如果 PDF 的目录没有序号，手动缩进无效吗

### ISSUE THREAD

**Issue by DiamondYuan** [ririv/QuickQutline#2]
![image](https://user-images.githubusercontent.com/9692408/132228483-4969068c-f22d-426e-a906-851c7fe5b983.png)
![image](https://user-images.githubusercontent.com/9692408/132228496-89423b64-5c8d-495f-998b-296ec64dd384.png)

**Comment by DiamondYuan** [comment]
```
彩图  4
第1版序言  11
第一部分  监督学习  25
	第1章  统计学习及监督学习概论  26
		1.1  统计学习  26
		1.2  统计学习的分类  27
			1.2.3  按算法分类  36
			1.2.4  按技巧分类  36
		1.3  统计学习方法三要素  38
			1.3.1  模型  38

		习题  56
	第2章  感知机  58
		2.1  感知机模型  58
		2.2  感知机学习策略  59
			2.2.1  数据集的线性可分性  59
			2.2.2  感知机学习策略  60
		2.3  感知机学习算法  61
			2.3.1  感知机学习算法的原始形式  61
			2.3.2  算法的收敛性  64
			2.3.3  感知机学习算法的对偶形式  66
		习题  69
参考文献 300
附录 A  梯度下降法  452
附录 B  牛顿法和拟牛顿法  454
```


![image](https://user-images.githubusercontent.com/9692408/132229354-2b4ba826-c375-44f1-b86f-3c82db204843.png)


“习题”应该是在第二章里面的？

**Comment by ririv** [comment]
将右下角改为 按缩进
